version: "3.3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - redis
  redis:
    ports:
      - "6379:6379"
    image: redis
