== Тест Redis

Использованы Spring Boot (v2.2.4), Thymeleaf, Bootstrap 4

=== Запуск

[source,shell script]
----
git clone https://github.com/cherepakhin/redis1.git
cd redis1
mvn spring-boot:run
----

Перед тестом нужно запустить Redis на локальной машине: redis-server

Проверить работу по адресу http://localhost:8080

=== Докеризация

* _Dockerfile_ - настройка image docker
* _create_docker_image.sh_ - создание docker image
* _run_docker.sh_ - запуск docker image
* _docker-compose.yaml_ - запуск проекта и redis сервера в docker (запуск #docker-compose up#).
** Порт 8080 для проверки работы приложения
** Порт 6379 - для доступа к redis-server
* _push_docker_image.sh_ - экспорт в docker hub

=== Переменные окружения (enviropment)

* _REDIS_HOST_ - адрес Redis сервиса. По умлчанию localhost
* _REDIS_PORT_ - номер порта Redis сервиса. По умолчанию 6379

=== Kubernetes

* kuber/redis1-deploy.yaml - манифест развертывания deployment сервиса и клиента Redis в Kubernetes

Развертывание в Kubernetes
[source,shell script]
----
kubectl apply -f kuber/redis1-deploy.yaml
----

Проверка работы сервера
[source,shell script]
----
kubectl port-forward service/redis-service 6379
$ redis-cli
127.0.0.1:6379> keys *
(empty list or set)
127.0.0.1:6379> set k1 v1
OK
127.0.0.1:6379> get k1
"v1"
127.0.0.1:6379> exit
----

Проверка работы клиента
[source,shell script]
----
kubectl port-forward service/redis-client-service 8080
----

Проверить работу по адресу http://localhost:8080
