---
# Pod Redis server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serverName }}
  labels:
    app: {{ .Values.serverName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.serverName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serverName }}
    spec:
      containers:
        - name: {{ .Values.serverName }}
          image: redis
          ports:
            - containerPort: 6379

---
# Redis service
kind: Service
apiVersion: v1
metadata:
  name: redis-service
spec:
  selector:
    app: {{ .Values.serverName }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
# Redis client
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.clientName }}
  labels:
    app: {{ .Values.clientName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.clientName }}
  template:
    metadata:
      labels:
        app: {{ .Values.clientName }}
    spec:
      containers:
        - name: {{ .Values.clientName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 8080

---
# Redis  Client Service
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.clientName }}-service
spec:
  selector:
    app: {{ .Values.clientName }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
